### ISSUE TITLE
FPM build error at 92%: read-from-json.f90

### ISSUE THREAD

**Issue by JordanWelsman** [sourceryinstitute/dag#60]
# Description
When building `dag` with `fpm test`, there is a compilation error when compiling `read-from-json.f90`

# Error message
Bash (`zsh`) error message:
```
...
vertex_m.f90                           done.
dag_m.f90                              done.
vertex_s.f90                           done.
dag-to-dot.f90                         done.
read-from-json.f90                     failed.
[  92%]Compiling...
example/read-from-json.f90:27:20:

   27 |       json_object = parsed_json%value_()
      |                    1
Error: Cannot convert CLASS(json_value_t) to CLASS(json_object_t) at (1)
<ERROR> Compilation failed for object " example_read-from-json.f90.o "
<ERROR>stopping due to failed compilation
STOP 1
```

# To Reproduce
- Clone the main branch (`git clone https://github.com/sourceryinstitute/dag.git`)
- Move forward into the `dag` directory (`cd dag/`)
- Build and test in shell (`fpm test`)
  - Error will occur when building `read-from-json.f90`.

# Notes
- Can not restart compilation process by issuing `fpm test` again

**Comment by rouson** [comment]
@everythingfunctional could you take a look at this?  Ideally, we'll use the DAG library for the FEATS demo paper.

**Comment by everythingfunctional** [comment]
I'm planning to upgrade the FEATS dependencies soon, and this will certainly be a part of that.
